import { Project } from "@/types";

import portfolioImage from "@/images/portfolio/index.webp";
import skymapImage from "@/images/skymap/main.webp";
import yaCheezImage from "@/images/yacheez/index.webp";
import pineImage from "@/images/pine/index.webp";
import pineDocsImage from "@/images/pine/docs.webp";
import neoBotImage from "@/images/neo-bot/card.webp";
import fueloneImage from "@/images/fuelone/index.webp";
import mentauraImage from "@/images/mentaura/index.webp";
import khattImage from "@/images/khatt/index.webp";
import jamaImage from "@/images/jama/index.webp";
import keplerfluxImage from "@/images/keplerflux/index.webp";

const projects = {
  Jama: {
    image: jamaImage,
    name: "Jama",
    shortDescription: "For the businesses struggling to get their invoices FBR compliant",
    description: "Create compliant invoices, submit them to FBR in real-time, and get verified QR codes - all from one dashboard built for Pakistani businesses and chartered accountants.",
    url: "https://jama.pk",
    techStack: ["react", "typescript", "tailwindcss", "docker", "laravel"]
  },
  Khatt: {
    image: khattImage,
    name: "Khatt",
    shortDescription: "A modern, ad-free Pakistani email platform built for individuals and businesses.",
    description: "A modern, ad-free Pakistani email platform built for individuals and businesses. Get your own .pk address with native Urdu support — private, fast, and clutter-free. Currently in closed beta.",
    url: "https://khatt.pk",
    techStack: ["nextjs", "typescript", "tailwindcss", "docker", "django", "postgresql", "stalwart"]
  },
  KeplerFlux: {
    image: keplerfluxImage,
    name: "KeplerFlux",
    shortDescription: "A HIPAA-compliant mini EHR with AI-powered auto transcription and clinical note generation.",
    description: "A HIPAA-compliant mini EHR with AI-powered auto transcription and clinical note generation. Designed to reduce documentation overhead for healthcare practitioners and streamline the patient encounter workflow.",
    // url: "https://keplerflux.com",
    techStack: ["react", "typescript", "tailwindcss", "django", "python", "postgresql", "docker"]
  },
  FuelOne: {
    image: fueloneImage,
    name: "FuelOne",
    shortDescription: "A fleet management and royalty card platform tailored for Oil Marketing Companies (OMCs).",
    description: "A fleet management and royalty card platform tailored for Oil Marketing Companies (OMCs). FuelOne enables real-time fuel tracking, card-based transactions, and performance insights for fleets and individual consumers alike. Built for scalability, security, and ease of integration.",
    url: "https://fuelone.neoflux.pk",
    techStack: ["laravel", "react", "php", "tailwindcss", "mysql", "docker", "kotlin", "jetpack-compose", "Smart Card Programming", "Google APIs"]
  },
  Mentaura: {
    image: mentauraImage,
    name: "Mentaura",
    description: "A mental health assessment platform that helps users gain insights into their emotional well-being. By answering a short series of questions, users receive a preliminary diagnosis generated by an intelligent system—designed to encourage self-awareness and guide next steps toward care.",
    notice: "The owner has discontinued the project and the domain is no longer active.",
    techStack: ["laravel", "php", "tailwindcss", "mysql", "react", "figma"]
  },
  NeoDiscordBot: {
    image: neoBotImage,
    name: "Neo Discord Bot",
    description: "A modular, Python-based Discord bot designed for community engagement and automation. Built with pycord, it features a scalable architecture using cogs, integrates with SQLite for persistent data storage, and includes utilities for streamlined command handling.",
    url: "https://pine.raahimfareed.com",
    techStack: ["pycord", "python", "sqlite"]
  },
  Pine: {
    image: pineImage,
    altImage: pineDocsImage,
    name: "Pine",
    shortDescription: "Pine is a minimalist PHP micro-framework designed for developers who value simplicity and full control.",
    description: "Pine is a minimalist PHP micro-framework designed for developers who value simplicity and full control. With an intuitive syntax and a flexible architecture, Pine empowers you to build applications effortlessly—customizing everything down to the grain.",
    url: "https://pine.raahimfareed.com",
    gitUrl: "https://github.com/raahimfareed/pine",
    techStack: ["php", "html", "css", "javascript", "tailwindcss", "docker", "pine"]
  },
  PineDocs: {
    image: pineDocsImage,
    name: "Pine Docs",
    description: "Pine Docs is the official documentation website. It is used as a guide and a reference page for the Pine framework which developers can use whenever they need to!",
    url: "https://pine.raahimfareed.com",
    techStack: ["nextjs", "html", "css", "javascript", "tailwindcss", "vercel", "md"]
  },
  Portfolio: {
    image: portfolioImage,
    name: "Portfolio",
    description: "You're currently on the live version of this project! This is my personal portfolio that encases the who, what and how of me. Enjoy your stay here",
    url: "https://raahimfareed.com",
    techStack: ["nextjs", "tailwindcss", "typescript", "vercel"]
  },
  SkyMap: {
    image: skymapImage,
    name: "SkyMap",
    description: "A virtual planetarium application to enhance research and learning.",
    techStack: ["unity", "csharp", "figma", "python", "sqlite"]
  },
  YaCheez: {
    image: yaCheezImage,
    name: "YaCheez",
    description: "An e-commerce platform offering a curated selection of trending lifestyle products across categories like home essentials, electronics, health & beauty, and fashion. Designed for seamless user experience and optimized for mobile, Yacheez delivers nationwide with free shipping.",
    notice: "The owner has, as of recently, switched to shopify therefore the actual project is no longer accessible.",
    url: "https://yacheez.com",
    techStack: ["laravel", "javascript", "alpinejs", "tailwindcss", "docker", "mysql"]
  }
} satisfies Record<string, Project>;

export type ProjectKey = keyof typeof projects;

export const projectList: Project[] = Object.values(projects);

export default projects;
